version: "3.0"
services:
    plogging-redis:
        image: "redis"
        volumes:
         - /data_1/redis_data:/data
        command: redis-server --requirepass ******* --appendonly yes
        ports:
          - "6379:6379"
        networks:
          - compose-networks
    plogging-mongo:
        image: "mongo"
        volumes:
         - /data_1/mongodb_data:/data/db
        ports:
          - "27017:27017"
        environment:
          - MONGO_INITDB_ROOT_USERNAME=****
          - MONGO_INITDB_ROOT_PASSWORD=*********
        networks:
          - compose-networks
    plogging-mariadb:
        build: 
          context: .
          dockerfile: ./mariadb.Dockerfile
        volumes:
          - /data_1/mysql_data:/var/lib/mysql
        ports: 
          - "3306:3306"
        environment:
          - MYSQL_ROOT_USER=****
          - MYSQL_ROOT_PASSWORD=********
        networks:
          - compose-networks

networks:
  compose-networks:
